export type BusinessLang = 'uk' | 'ru';

type LabelMap = Record<string, { uk: string; ru: string }>;

export const BUSINESS_SPHERE_LABELS: LabelMap = {
  beauty_care: { uk: 'Красота та догляд', ru: 'Красота и уход' },
  health_sport: { uk: "Здоров'я та спорт", ru: 'Здоровье и спорт' },
  auto_transport: { uk: 'Авто та транспорт', ru: 'Авто и транспорт' },
  repair_construction: { uk: 'Ремонт та будівництво', ru: 'Ремонт и строительство' },
  home_services: { uk: 'Дім та побутові послуги', ru: 'Дом и бытовые услуги' },
  food_gastro: { uk: 'Їжа та гастрономія', ru: 'Еда и гастрономия' },
  retail: { uk: 'Магазини та торгівля', ru: 'Магазины и торговля' },
  education: { uk: 'Освіта та навчання', ru: 'Образование и обучение' },
  real_estate: { uk: 'Нерухомість', ru: 'Недвижимость' },
  finance_insurance: { uk: 'Фінанси та страхування', ru: 'Финансы и страхование' },
  legal_docs: { uk: 'Право та документи', ru: 'Право и документы' },
  it_marketing: { uk: 'IT, маркетинг та дизайн', ru: 'IT, маркетинг и дизайн' },
  photo_events: { uk: 'Фото, відео та заходи', ru: 'Фото, видео и мероприятия' },
  tourism: { uk: 'Туризм та подорожі', ru: 'Туризм и путешествия' },
  other: { uk: 'Інше', ru: 'Другое' },
};

export const BUSINESS_DIRECTION_LABELS: LabelMap = {
  hairdresser: { uk: 'Перукарня', ru: 'Парикмахерская' },
  barbershop: { uk: 'Барбершоп', ru: 'Барбершоп' },
  manicure: { uk: 'Манікюр', ru: 'Маникюр' },
  pedicure: { uk: 'Педикюр', ru: 'Педикюр' },
  brows: { uk: 'Брови', ru: 'Брови' },
  lashes: { uk: 'Вії', ru: 'Ресницы' },
  cosmetology: { uk: 'Косметологія', ru: 'Косметология' },
  makeup: { uk: 'Візаж', ru: 'Визаж' },
  tattoo_piercing: { uk: 'Тату / пірсинг', ru: 'Тату / пирсинг' },
  massage: { uk: 'Масаж', ru: 'Массаж' },
  fitness: { uk: 'Фітнес', ru: 'Фитнес' },
  personal_trainer: { uk: 'Персональний тренер', ru: 'Персональный тренер' },
  yoga: { uk: 'Йога', ru: 'Йога' },
  rehabilitation: { uk: 'Реабілітація', ru: 'Реабилитация' },
  sports_school: { uk: 'Спортивна школа', ru: 'Спортивная школа' },
  car_dealer: { uk: 'Автосалон', ru: 'Автосалон' },
  car_service: { uk: 'Автосервіс', ru: 'Автосервис' },
  detailing: { uk: 'Детейлінг', ru: 'Детейлинг' },
  tire_service: { uk: 'Шиномонтаж', ru: 'Шиномонтаж' },
  auto_electrician: { uk: 'Автоелектрик', ru: 'Автоэлектрик' },
  tow_truck: { uk: 'Евакуатор', ru: 'Эвакуатор' },
  shipping: { uk: 'Перевезення', ru: 'Перевозки' },
  car_rental: { uk: 'Оренда авто', ru: 'Аренда авто' },
  apartment_renovation: { uk: 'Ремонт квартири', ru: 'Ремонт квартир' },
  construction: { uk: 'Будівництво', ru: 'Строительство' },
  electrician: { uk: 'Електрик', ru: 'Электрик' },
  plumber: { uk: 'Сантехнік', ru: 'Сантехник' },
  painter: { uk: 'Маляр', ru: 'Маляр' },
  tiler: { uk: 'Плиточник', ru: 'Плиточник' },
  windows_doors: { uk: 'Вікна / двері', ru: 'Окна / двери' },
  custom_furniture: { uk: 'Меблі на замовлення', ru: 'Мебель на заказ' },
  cleaning: { uk: 'Клінінг', ru: 'Клининг' },
  moving: { uk: 'Переїзди', ru: 'Переезды' },
  furniture_assembly: { uk: 'Збірка меблів', ru: 'Сборка мебели' },
  appliance_repair: { uk: 'Ремонт техніки', ru: 'Ремонт техники' },
  gardening: { uk: 'Садові роботи', ru: 'Садовые работы' },
  hausmeister: { uk: 'Hausmeister', ru: 'Hausmeister' },
  restaurant: { uk: 'Ресторан', ru: 'Ресторан' },
  cafe: { uk: 'Кафе', ru: 'Кафе' },
  bakery: { uk: 'Пекарня', ru: 'Пекарня' },
  confectionery: { uk: 'Кондитерська', ru: 'Кондитерская' },
  catering: { uk: 'Кейтеринг', ru: 'Кейтеринг' },
  food_delivery: { uk: 'Доставка їжі', ru: 'Доставка еды' },
  grocery: { uk: 'Продуктовий магазин', ru: 'Продуктовый магазин' },
  clothing: { uk: 'Одяг', ru: 'Одежда' },
  shoes: { uk: 'Взуття', ru: 'Обувь' },
  cosmetics_shop: { uk: 'Косметика', ru: 'Косметика' },
  electronics_shop: { uk: 'Електроніка', ru: 'Электроника' },
  furniture_shop: { uk: 'Меблі', ru: 'Мебель' },
  home_goods: { uk: 'Товари для дому', ru: 'Товары для дома' },
  kids_goods: { uk: 'Дитячі товари', ru: 'Детские товары' },
  flowers: { uk: 'Квіти', ru: 'Цветы' },
  pet_supplies: { uk: 'Зоотовари', ru: 'Зоотовары' },
  language_school: { uk: 'Мовні школи', ru: 'Языковые школы' },
  tutoring: { uk: 'Репетитори', ru: 'Репетиторы' },
  driving_school: { uk: 'Автошколи', ru: 'Автошколы' },
  kids_center: { uk: 'Дитячі центри', ru: 'Детские центры' },
  courses: { uk: 'Курси', ru: 'Курсы' },
  vocational_training: { uk: 'Професійне навчання', ru: 'Профессиональное обучение' },
  real_estate_agency: { uk: 'Агентство нерухомості', ru: 'Агентство недвижимости' },
  realtor: { uk: 'Ріелтор', ru: 'Риелтор' },
  rental: { uk: 'Оренда', ru: 'Аренда' },
  property_management: { uk: 'Управління нерухомістю', ru: 'Управление недвижимостью' },
  accounting: { uk: 'Бухгалтерія', ru: 'Бухгалтерия' },
  taxes: { uk: 'Податки', ru: 'Налоги' },
  insurance: { uk: 'Страхування', ru: 'Страхование' },
  financial_services: { uk: 'Фінансові послуги', ru: 'Финансовые услуги' },
  legal_services: { uk: 'Юридичні послуги', ru: 'Юридические услуги' },
  translations: { uk: 'Переклади', ru: 'Переводы' },
  documents: { uk: 'Документи', ru: 'Документы' },
  immigration_services: { uk: 'Імміграційні послуги', ru: 'Иммиграционные услуги' },
  web_development: { uk: 'Розробка сайтів', ru: 'Разработка сайтов' },
  it_services: { uk: 'IT', ru: 'IT' },
  smm: { uk: 'SMM', ru: 'SMM' },
  advertising: { uk: 'Реклама', ru: 'Реклама' },
  graphic_design: { uk: 'Графічний дизайн', ru: 'Графический дизайн' },
  branding: { uk: 'Branding', ru: 'Branding' },
  seo: { uk: 'SEO', ru: 'SEO' },
  photographer: { uk: 'Фотограф', ru: 'Фотограф' },
  videographer: { uk: 'Відеограф', ru: 'Видеограф' },
  dj: { uk: 'DJ', ru: 'DJ' },
  host: { uk: 'Ведучий', ru: 'Ведущий' },
  decor: { uk: 'Декор', ru: 'Декор' },
  event_planning: { uk: 'Організація заходів', ru: 'Организация мероприятий' },
  travel_agency: { uk: 'Турагентство', ru: 'Турагентство' },
  excursions: { uk: 'Екскурсії', ru: 'Экскурсии' },
  transfers: { uk: 'Трансфери', ru: 'Трансферы' },
  tourism_services: { uk: 'Туристичні послуги', ru: 'Туристические услуги' },
};

export function resolveBusinessLabel(
  map: LabelMap,
  id: string,
  lang: BusinessLang
): string {
  return map[id]?.[lang] || id;
}
