// Список німецьких міст (найбільші та популярні)
export const germanCities = [
  // Найбільші міста (100,000+)
  'Berlin',
  'Hamburg',
  'München',
  'Köln',
  'Frankfurt am Main',
  'Stuttgart',
  'Düsseldorf',
  'Dortmund',
  'Essen',
  'Leipzig',
  'Bremen',
  'Dresden',
  'Hannover',
  'Nürnberg',
  'Duisburg',
  'Bochum',
  'Wuppertal',
  'Bielefeld',
  'Bonn',
  'Münster',
  'Karlsruhe',
  'Mannheim',
  'Augsburg',
  'Wiesbaden',
  'Gelsenkirchen',
  'Mönchengladbach',
  'Braunschweig',
  'Chemnitz',
  'Kiel',
  'Aachen',
  'Halle (Saale)',
  'Magdeburg',
  'Freiburg im Breisgau',
  'Krefeld',
  'Lübeck',
  'Oberhausen',
  'Erfurt',
  'Mainz',
  'Rostock',
  'Kassel',
  'Hagen',
  'Hamm',
  'Saarbrücken',
  'Mülheim an der Ruhr',
  'Potsdam',
  'Ludwigshafen am Rhein',
  'Oldenburg',
  'Leverkusen',
  'Osnabrück',
  'Solingen',
  'Heidelberg',
  'Herne',
  'Neuss',
  'Darmstadt',
  'Paderborn',
  'Regensburg',
  'Ingolstadt',
  'Würzburg',
  'Fürth',
  'Wolfsburg',
  'Offenbach am Main',
  'Ulm',
  'Heilbronn',
  'Pforzheim',
  'Göttingen',
  'Bottrop',
  'Trier',
  'Recklinghausen',
  'Reutlingen',
  'Bremerhaven',
  'Koblenz',
  'Bergisch Gladbach',
  'Jena',
  'Remscheid',
  'Erlangen',
  'Moers',
  'Siegen',
  'Hildesheim',
  'Salzgitter',
  'Wedel',
  'Pinneberg',
  'Ahrensburg',
  'Reinbek',
  'Barsbüttel',
  'Elmshorn',
  'Buxtehude',
  
  // Середні міста (50,000-100,000)
  'Cottbus',
  'Gera',
  'Kaiserslautern',
  'Schwerin',
  'Witten',
  'Gütersloh',
  'Iserlohn',
  'Zwickau',
  'Düren',
  'Ratingen',
  'Tübingen',
  'Flensburg',
  'Lünen',
  'Villingen-Schwenningen',
  'Marl',
  'Konstanz',
  'Minden',
  'Worms',
  'Velbert',
  'Neumünster',
  'Norderstedt',
  'Delmenhorst',
  'Wilhelmshaven',
  'Viersen',
  'Gladbeck',
  'Dorsten',
  'Rheine',
  'Detmold',
  'Troisdorf',
  'Castrop-Rauxel',
  'Lüneburg',
  'Marburg',
  'Arnsberg',
  'Lüdenscheid',
  'Bamberg',
  'Bayreuth',
  'Bocholt',
  'Dinslaken',
  'Unna',
  'Plauen',
  'Aschaffenburg',
  'Fulda',
  'Lippstadt',
  'Kempten (Allgäu)',
  'Landshut',
  'Weimar',
  'Sindelfingen',
  'Neuwied',
  'Brandenburg an der Havel',
  'Rosenheim',
  'Friedrichshafen',
  'Offenburg',
  'Stralsund',
  'Greifswald',
  'Hameln',
  'Göppingen',
  'Hürth',
  'Stolberg (Rheinland)',
  'Eschweiler',
  'Sankt Augustin',
  'Görlitz',
  'Hilden',
  'Waiblingen',
  'Langenfeld (Rheinland)',
  'Bergheim',
  'Schwäbisch Gmünd',
  'Garbsen',
  'Wesel',
  'Emden',
  'Sankt Ingbert',
  'Backnang',
  'Wetzlar',
  'Neustadt an der Weinstraße',
  'Königswinter',
  'Grevenbroich',
  'Kerpen',
  'Rüsselsheim am Main',
  'Frankenthal (Pfalz)',
  'Bergkamen',
  'Ravensburg',
  'Hennef (Sieg)',
  'Meerbusch',
  'Bad Homburg vor der Höhe',
  'Eisenach',
  'Lörrach',
  'Freising',
  'Leonberg',
  'Bad Salzuflen',
  'Frechen',
  'Langen',
  'Gotha',
  'Dormagen',
  'Bruchsal',
  'Neustadt am Rübenberge',
  'Albstadt',
  'Halberstadt',
  'Peine',
  'Kamen',
  'Erftstadt',
  'Kaarst',
  'Rottenburg am Neckar',
  'Bietigheim-Bissingen',
  'Borken',
  'Bensheim',
  'Bautzen',
  'Pirna',
  'Nettetal',
  'Hof',
  'Ahaus',
  'Bühl',
  'Baden-Baden',
  'Ettlingen',
  'Pulheim',
  'Schweinfurt',
  'Warendorf',
  'Euskirchen',
  'Geldern',
  'Kempen',
  'Bad Oeynhausen',
  'Speyer',
  'Passau',
  'Rastatt',
  'Wittenberg',
  'Merseburg',
  'Suhl',
  'Nordhorn',
  'Bitterfeld-Wolfen',
  'Zittau',
  'Wismar',
  'Gummersbach',
  'Weißenfels',
  'Schwandorf',
  'Sondershausen',
  'Grimma',
  'Wernigerode',
  'Burg',
  'Zeitz',
  'Sangerhausen',
  'Naumburg (Saale)',
  'Eisleben',
  'Quedlinburg',
  'Stendal',
  'Wittenberge',
  'Gardelegen',
  'Salzwedel',
  'Tangermünde',
  'Osterburg',
  'Havelberg',
  'Arendsee',
  'Seehausen',
  'Werben',
  'Schönhausen',
  'Rathenow',
  'Premnitz',
  'Friesack',
  'Nauen',
  'Falkensee',
  'Ketzin',
  'Brandenburg',
  'Potsdam',
  'Werder (Havel)',
  'Teltow',
  'Stahnsdorf',
  'Kleinmachnow',
  'Michendorf',
  'Beelitz',
  'Treuenbrietzen',
  'Jüterbog',
  'Luckenwalde',
  'Baruth/Mark',
  'Zossen',
  'Mittenwalde',
  'Königs Wusterhausen',
  'Eichwalde',
  'Schulzendorf',
  'Zeuthen',
  'Wildau',
  'Königswusterhausen',
  'Bestensee',
  'Märkisch Buchholz',
  'Lieberose',
  'Lübben (Spreewald)',
  'Lübbenau/Spreewald',
  'Vetschau/Spreewald',
  'Calau',
  'Senftenberg',
  'Lauchhammer',
  'Schwarzheide',
  'Ruhland',
  'Ortrand',
  'Großräschen',
  'Finsterwalde',
  'Doberlug-Kirchhain',
  'Sonnewalde',
  'Drebkau',
  'Welzow',
  'Spremberg',
  'Hoyerswerda',
  'Wittichenau',
  'Königswartha',
  'Neschwitz',
  'Radibor',
  'Großdubrau',
  'Malschwitz',
  'Bautzen',
  'Kirschau',
  'Schirgiswalde-Kirschau',
  'Crostwitz',
  'Puschwitz',
  'Nebelschütz',
  'Räckelwitz',
  'Panschwitz-Kuckau',
  'Ralbitz-Rosenthal',
  'Göda',
  'Doberschau-Gaußig',
  'Königswartha',
  'Neschwitz',
  'Radibor',
  'Großdubrau',
  'Malschwitz',
  'Bautzen',
  'Kirschau',
  'Schirgiswalde-Kirschau',
  'Crostwitz',
  'Puschwitz',
  'Nebelschütz',
  'Räckelwitz',
  'Panschwitz-Kuckau',
  'Ralbitz-Rosenthal',
  'Göda',
  'Doberschau-Gaußig',
].sort((a, b) => a.localeCompare(b, 'de'));

// Функція пошуку міст
export function searchGermanCities(query: string, limit: number = 10): string[] {
  const normalizedQuery = query.toLowerCase().trim();
  
  if (!normalizedQuery) return germanCities.slice(0, limit);
  
  return germanCities
    .filter(city => city.toLowerCase().includes(normalizedQuery))
    .slice(0, limit);
}

// Функція перевірки чи є місто в списку
export function isGermanCityValid(city: string): boolean {
  return germanCities.some(c => 
    c.toLowerCase() === city.toLowerCase()
  );
}

