"""Зворотна сумісність: parser.db → parser.storage."""

from parser.storage import *  # noqa: F403
from parser.storage import (
    BASE_DIR,
    DB_PATH,
    cleanup_stale_parsed_photos,
    copy_parser_images_to_public,
    create_marketplace_listing,
    ensure_parsed_items_table,
    fingerprint_parsed_text,
    fingerprint_title_desc,
    get_connection,
    get_or_create_bot_user,
    get_parsed_item_by_admin_msg,
    get_parsed_item_by_id,
    insert_parsed_item,
    parsed_item_content_hash_exists,
    parsed_item_exists,
    parsed_item_is_raw_duplicate,
    parsed_item_is_semantic_duplicate,
    set_admin_message_id,
    set_marketplace_listing_id,
    update_parsed_item_status,
)

__all__ = [
    "BASE_DIR",
    "DB_PATH",
    "cleanup_stale_parsed_photos",
    "copy_parser_images_to_public",
    "create_marketplace_listing",
    "ensure_parsed_items_table",
    "fingerprint_parsed_text",
    "fingerprint_title_desc",
    "get_connection",
    "get_or_create_bot_user",
    "get_parsed_item_by_admin_msg",
    "get_parsed_item_by_id",
    "insert_parsed_item",
    "parsed_item_content_hash_exists",
    "parsed_item_exists",
    "parsed_item_is_raw_duplicate",
    "parsed_item_is_semantic_duplicate",
    "set_admin_message_id",
    "set_marketplace_listing_id",
    "update_parsed_item_status",
]
